#ifndef SWAY_OIS_MOUSEWHEELSCROLLACTIONS_HPP
#define SWAY_OIS_MOUSEWHEELSCROLLACTIONS_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(ois)

enum class MouseWheelScrollAction : u32_t { UP, DOWN, Latest };

NAMESPACE_END(ois)
NAMESPACE_END(sway)

#endif  // SWAY_OIS_MOUSEWHEELSCROLLACTIONS_HPP
